baseURL = 'https://colonialbiker123.github.io'
languageCode = 'en-us'
title = 'Sumukh Kesarla'
theme = "hugo-coder"
defaultContentLanguage = "en"

[pagination]
  pagerSize = 20

[params]
  author = "Sumukh Kesarla"
  description = "Cyber Security | Research"
  keywords = "blog,security"
  info = ["Cybersecurity Engineer", "Research"]
  avatarURL = "images/avatar.jpg"
  colorScheme = "auto"
  hideColorSchemeToggle = false
  toc = true

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope"
  weight = 3
  url = "mailto:colonialbiker123@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/colonialbiker123/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 2
  url = "https://linkedin.com/in/sumukh-kesarla/"

[languages.en]
  languageName = "English"
  weight = 1

[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[[menu.main]]
  name = "Article"
  weight = 2
  url = "article/"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    ordered = true
    endLevel = 4
